name: Supabase Database Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'migrations/**'  # Only trigger on changes to migration files
  workflow_dispatch:     # Allow manual triggering

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Link to Supabase project
      run: |
        supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_ID }}" --password "${{ secrets.SUPABASE_DB_PASSWORD }}"
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    
    - name: Apply migrations
      run: |
        supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
