name: Supabase Database Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'migrations/**'  # Only trigger on changes to migration files
  workflow_dispatch:     # Allow manual triggering

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Link to Supabase project
      env:
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        supabase link --project-ref "$SUPABASE_PROJECT_ID" --password "$SUPABASE_DB_PASSWORD"
    
    - name: Apply migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        supabase db push
